### ISSUE TITLE
Hover fixes

### ISSUE THREAD

**Issue by SashaScholar6** [Scholar-6/brillder#2181]
<img width="520" alt="Screenshot 2020-10-23 at 16 25 13" src="https://user-images.githubusercontent.com/59654112/97015996-7f28a500-154c-11eb-87a1-ec718a81b232.png">

- [x] Top and Subtopic should be directly below title (not one line in between

- [x] instead use that line to have Open Question on two lines

- [x] Editor Name Surname should have only one space between Name and Surname

**Comment by ivanromakh** [comment]
@SashaScholar6 I think its better for Farman to do this there is too much css.

**Comment by SashaScholar6** [comment]
ok

**Comment by farman9849** [comment]
The task for @ivanromakh:
instead, use that line to have Open Question on two lines
please add 150 / 170 character limit to this point

Reason:
Ellipsis is added to one line only, because of no-wrap

Solution:
Will add simp[le 3 dots image with CSS at the end on the line in second-line or if you can do that dynamically after character limit it would be more appropriate
