### ISSUE TITLE
Fixes to tables

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3348]
- [x] Cannot breakline inside table (but still need to be able to enter a breakline to create a line after table)
- [x] Cannot add bullet points inside table (Wont do this because bounty on this and probably a lot of work).
- [x] Table icon still showing inside word/line highlight answer box

- [x] No border around tables in the phone preview

- [x] Add some padding to left side of table
![image](https://user-images.githubusercontent.com/58778078/117688865-184d9f00-b1b1-11eb-8214-2dadfc3758db.png)

**Comment by william-gooch** [comment]
@scholar6admin Re: points 1 and 2, this is an issue with the default quill table module.
There's an alternative module https://github.com/soccerloway/quill-better-table which could work instead. That has multiline cells, but still no lists. I also imagine it will be incompatible with quill-table-ui since it implements its own UI (which isn't as nice) but this isn't certain.
There's also the option of forking Quill and trying to fix it ourselves, but that would likely be quite difficult. https://github.com/quilljs/quill/issues/117
There is apparently a $5,000 bounty out for it, though? So I imagine if it were an easy fix then it would have been fixed already.

**Comment by scholar6admin** [comment]
@SashaScholar6 can we discuss
