### ISSUE TITLE
Redirect back to intended page after login

### ISSUE THREAD

**Issue by scholar6admin** [Scholar-6/brillder#3474]
@william-gooch this seems to work sometimes. But not others. For example it doesnt work for admin trying to access a page such as this with google login.
https://dev-app.brillder.com/build/brick/700/investigation/question-component/236405

**Comment by william-gooch** [comment]
@scholar6admin At the moment, for me at least, I can't seem to log in with Google _at all_.
Google login is way more difficult because it redirects the user away from our app. So any data that was stored in Redux is lost.
I might be able to implement it with local storage or cookies if that would be preferable?

**Comment by scholar6admin** [comment]
@william-gooch  Cant we do all of it in the url?

**Comment by william-gooch** [comment]
@scholar6admin Hmm... that might be possible actually. Let me try it.
